# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :beta do
    get_provisioning_profile(
      adhoc: true,
      filename: "myFile.mobileprovision",
      username: "lovesunyujian@126.com",
      app_identifier: "com.rider.application",
      team_id: "4XN6N3ZU8Q"
    )
    build_app(export_method: "ad-hoc", configuration: "Release")
    pgyer(api_key: "a4008aa5e8a4a0e210f2a4d749e9b789", user_key: "87bba40ee29c229b4c3bbc32d505e15a")
  end
end
